# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'question.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication
from answer import Answer_str, Answer_m


class Question(QtWidgets.QDialog):
    def __init__(self, value):
        super(Question, self).__init__()
        self.arr = [""]
        self.dic = {
            "C вариантами ответа": Answer_m,
            "Без вариантов ответа": Answer_str
        }
        self.title = value[0]
        self.ans = value[1]
        self.manswers = value[2]
        self.setupUi(self)

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(566, 382)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(470, 20, 81, 51))
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.type = QtWidgets.QComboBox(Dialog)
        self.type.setGeometry(QtCore.QRect(60, 20, 401, 22))
        self.type.setObjectName("type")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(26, 20, 21, 20))
        self.label.setObjectName("label")
        self.question_title = QtWidgets.QLineEdit(Dialog)
        self.question_title.setGeometry(QtCore.QRect(60, 90, 411, 20))
        self.question_title.setObjectName("question_title")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 90, 47, 21))
        self.label_2.setObjectName("label_2")
        self.answer_box = QtWidgets.QWidget(Dialog)
        self.answer_box.setGeometry(QtCore.QRect(60, 120, 411, 251))
        self.answer_box.setObjectName("verticalLayoutWidget")
        self.answer = QtWidgets.QVBoxLayout(self.answer_box)
        self.answer.setContentsMargins(0, 0, 0, 0)
        self.answer.setObjectName("verticalLayout")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Тип"))
        self.label_2.setText(_translate("Dialog", "Вопрос"))

        self.question_title.setText(self.title)

        if self.manswers == "__Entry__":
            self.type.addItems(["Без вариантов ответа", "C вариантами ответа"])
            self.now_type = Answer_str(self.ans, self.manswers)
        else:
            self.type.addItems(["C вариантами ответа", "Без вариантов ответа"])
            self.now_type = self.dic[self.type.currentText()](self.ans, self.manswers)
        self.answer.addWidget(self.now_type)
        self.type.currentTextChanged.connect(self.change_ans_type)

    def change_ans_type(self):
        self.answer.itemAt(0).widget().deleteLater()
        self.now_type = self.dic[self.type.currentText()](self.ans, self.manswers)
        self.answer.addWidget(self.now_type)

    def accept(self):
        self.arr = [self.question_title.text()] + self.now_type.get_answer()
        super(Question, self).accept()


def ques(parent, value):
    exe = Question(value)
    exe.setAttribute(QtCore.Qt.WA_DeleteOnClose)
    if exe.exec_() == QtWidgets.QDialog.Accepted:
        parent.value = exe.arr


if __name__ == "__main__":
    print(ques())